// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "ProtoMessage.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ProtoMessageRoot

@implementation ProtoMessageRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - ProtoMessageRoot_FileDescriptor

static GPBFileDescriptor *ProtoMessageRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - ProtoMessage

@implementation ProtoMessage

@dynamic hasType, type;
@dynamic hasFrom, from;
@dynamic hasTo, to;
@dynamic hasTime, time;
@dynamic hasBody, body;

typedef struct ProtoMessage__storage_ {
  uint32_t _has_storage_[1];
  ProtoMessage_Type type;
  NSString *from;
  NSString *to;
  NSString *time;
  NSString *body;
} ProtoMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescriptionWithDefault fields[] = {
      {
        .defaultValue.valueEnum = ProtoMessage_Type_Chat,
        .core.name = "type",
        .core.dataTypeSpecific.enumDescFunc = ProtoMessage_Type_EnumDescriptor,
        .core.number = ProtoMessage_FieldNumber_Type,
        .core.hasIndex = 0,
        .core.offset = (uint32_t)offsetof(ProtoMessage__storage_, type),
        .core.flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldHasDefaultValue | GPBFieldHasEnumDescriptor),
        .core.dataType = GPBDataTypeEnum,
      },
      {
        .defaultValue.valueString = nil,
        .core.name = "from",
        .core.dataTypeSpecific.className = NULL,
        .core.number = ProtoMessage_FieldNumber_From,
        .core.hasIndex = 1,
        .core.offset = (uint32_t)offsetof(ProtoMessage__storage_, from),
        .core.flags = GPBFieldRequired,
        .core.dataType = GPBDataTypeString,
      },
      {
        .defaultValue.valueString = nil,
        .core.name = "to",
        .core.dataTypeSpecific.className = NULL,
        .core.number = ProtoMessage_FieldNumber_To,
        .core.hasIndex = 2,
        .core.offset = (uint32_t)offsetof(ProtoMessage__storage_, to),
        .core.flags = GPBFieldRequired,
        .core.dataType = GPBDataTypeString,
      },
      {
        .defaultValue.valueString = nil,
        .core.name = "time",
        .core.dataTypeSpecific.className = NULL,
        .core.number = ProtoMessage_FieldNumber_Time,
        .core.hasIndex = 3,
        .core.offset = (uint32_t)offsetof(ProtoMessage__storage_, time),
        .core.flags = GPBFieldRequired,
        .core.dataType = GPBDataTypeString,
      },
      {
        .defaultValue.valueString = nil,
        .core.name = "body",
        .core.dataTypeSpecific.className = NULL,
        .core.number = ProtoMessage_FieldNumber_Body,
        .core.hasIndex = 4,
        .core.offset = (uint32_t)offsetof(ProtoMessage__storage_, body),
        .core.flags = GPBFieldOptional,
        .core.dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ProtoMessage class]
                                     rootClass:[ProtoMessageRoot class]
                                          file:ProtoMessageRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescriptionWithDefault))
                                   storageSize:sizeof(ProtoMessage__storage_)
                                         flags:GPBDescriptorInitializationFlag_FieldsWithDefault];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum ProtoMessage_Type

GPBEnumDescriptor *ProtoMessage_Type_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Login\000Chat\000";
    static const int32_t values[] = {
        ProtoMessage_Type_Login,
        ProtoMessage_Type_Chat,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(ProtoMessage_Type)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:ProtoMessage_Type_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL ProtoMessage_Type_IsValidValue(int32_t value__) {
  switch (value__) {
    case ProtoMessage_Type_Login:
    case ProtoMessage_Type_Chat:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
